const test = async () => {
	console.log('begin');
	console.log('test 1');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 2');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 3');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 4');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 5');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 6');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 7');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 8');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 9');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 10');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 11');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 12');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 13');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 14');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 15');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 16');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 17');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 18');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 19');
	await new Promise((callback) => setTimeout(callback, 1000));
	console.log('test 20');
	console.log('end');
};

(async function main() {
	console.log('main - begin');
	// console.log(Number.MAX_SAFE_INTEGER);
	// console.log(Number.MAX_VALUE);
	// console.log(Number.MIN_SAFE_INTEGER);
	// console.log(Number.MIN_VALUE);
	// console.log(Number.POSITIVE_INFINITY);
	// console.log(Number.NEGATIVE_INFINITY);
	// console.log(Number.NaN);
	// console.log(Number.EPSILON);
	// const interval = setInterval(test, Number.MAX_SAFE_INTEGER);

	const interval = setInterval(test, 10000);
	console.log('interval:', interval);
	console.log('before timeout');
	await new Promise((callback) => setTimeout(callback, 11000));
	console.log('after timeout');
	console.log('before clear interval');
	clearInterval(interval);
	console.log('after clear interval');
	console.log('main - end');
})();
