#!/bin/bash

set -ex

mkdir -p resources/references/rujira

git submodule update --init --remote --force ./resources/references/rujira/contracts ./resources/references/rujira/api ./resources/references/rujira/ui
git submodule update --init --remote --force ./resources/references/rujira/contracts ./resources/references/rujira/api ./resources/references/rujira/ui

bun install

if [ ! -f "resources/configuration/production.yml" ]; then
	cp "resources/configuration/production.example.yml" "resources/configuration/production.yml"
fi

set +ex
