rujira:
  tokens:
    graphql: "<graphql token>" # Optional, but required if you want to use the GraphQL API. It is also possible to use the RUJIRA_TOKEN_GRAPHQL environment variable, in this case set this field to null.
  wallet:
    mnemonic: "<wallet mnemonic>" # Optional, but required if privateKey is not provided. It is also possible to use the RUJIRA_WALLET_MNEMONIC environment variable, in this case set this field to null.
    privateKey: "<wallet private key>" # Optional, but required if mnemonic is not provided. It is also possible to use the RUJIRA_WALLET_PRIVATE_KEY environment variable, in this case set this field to null.
    publicKeys:
      thor: "<wallet thor public key>" # Optional. It is also possible to use the RUJIRA_WALLET_PUBLIC_KEY_THOR environment variable, in this case set this field to null.
      ethereum: "<wallet ethereum public key>" # Optional. It is also possible to use the RUJIRA_WALLET_PUBLIC_KEY_ETHEREUM environment variable, in this case set this field to null.
strategy:
  pure_market_making:
    common:
      market: "THOR-RUJI/ETH-USDC"
      tickInterval: 60000 # 1 minute in milliseconds
      candles:
        initialLookbackInterval: 21600000 # 6 hours in milliseconds
        updateLookbackInterval: 300000 # 5 minutes in milliseconds
        maximumNumberOfCandlesKept: 500 # Maximum number of candles that is kept in memory
      orders:
        minimumTokenAmountPerOrder: 0 # Minimum token amount per order
        desiredTokenFreeBalancePercentagePerOrder: 10 # Desired token percentage of the free balance per order (0-100)
        desiredTokenFreeBalanceAmountPerOrder: 1 # Desired token free balance amount per order
        maximumTokenAmountPerOrder: 10 # Maximum token amount per order
      whenStart:
        cancelAllOrders: true
        withdrawAllFilledOrders: true
      whenStop:
        cancelAllOrders: true
        withdrawAllFilledOrders: true
      monitorProfitAndLoss:
        enabled: true
        maximumAllowedWalletLossFromInitialValue: 10 # 1 means 1%
        maximumAllowedWalletLossFromPreviousValue: 10 # 1 means 1%
      tasks:
        updateTokens:
          interval: 21600000 # 6 hours in milliseconds, to disable set it to null
        updateMarkets:
          interval: 21600000 # 6 hours in milliseconds, to disable set it to null
        updateIndicators:
          interval: 60000 # 1 minute in milliseconds, to disable set it to null
        updateOrderBook:
          interval: 30000 # 30 seconds in milliseconds, to disable set it to null
        monitorProfitAndLoss:
          interval: 60000 # 1 minute in milliseconds, to disable set it to null
      logger:
        level: "INFO"
    simple:
      orders:
        spreadPercentage: 10 # 1 means 1%
    enhanced:
      orders:
        minimumSpreadPercentage: 10 # // Minimum spread as a percentage of the middle price (example: 1 means 1%)
        bollingerBandsWidthSpreadWidthMultiplier: 1.2 # Multiplier for the spread using Bollinger Bands width (≈1.0–1.8)
        volumeWeightedAveragePriceSkewMultiplier: 0.8 # Pull intensity toward the volume weighted average price (≈0.5–1.2)
        maximumSkewPercentage: 0.40 # Maximum absolute skew as a percentage (example: 1 means 1%) (~0.4)
        volatilitySizeShrinkageMultiplier: 4.0 # Multiplier for size shrinkage based on average true range (≈3–6)
